table _measures
	lineageTag: 3b5b4d14-7f87-449d-ba5c-3418c25ab9f7

	measure _color_list_slicer = ```
			
			VAR seleccion = SELECTEDVALUE('_measures'[metrics])
			RETURN
			    SWITCH(
			        TRUE(),
			        seleccion = "Attack", "#E74C3C",       // Rojo suave (Tomato Red)
			        seleccion = "Defense", "#5DADE2",      // Celeste (Sky Blue)
			        seleccion = "Passing", "#27AE60",      // Verde amigable (Emerald)
			        "#D5D8DC"                              // Gris claro por defecto
			    )
			
			```
		lineageTag: e25b4956-fa3a-4c2b-a95a-33c29d55c192
		dataCategory: ImageUrl

	measure _slicer_attack_gif =
			
			"data:image/gif;base64,R0lGODlhgACAAPcAAP8AAP8AAP8AAP8AAP8AAP4AAP4AAP4AAP4AAP4AAP4AAD4A"
		lineageTag: 0471d4dd-8714-424a-a9d8-d322648b8e61
		dataCategory: ImageUrl

	measure _slicer_selected_value =
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(_measures[metrics]), "Attack", [_slicer_attack_gif],
			    SELECTEDVALUE(_measures[metrics]), "Defense", [_slicer_defence_gif],
			    SELECTEDVALUE(_measures[metrics]), "Passing", [_slicer_passing_gif]
			)
		formatString: 0
		lineageTag: c9e58679-e696-4f79-8733-6c5292967771

	measure _slicer_passing_gif =
			
			"data:image/gif;base64,R0lGODlhgACAAPcAAP8AAP8AAP8AAP8AAP4AAP4AAP4AAP4AAP4AAP4AAP4AADAA"
		lineageTag: a07eda6f-cd89-4862-b425-dbe0d367cd2a
		dataCategory: ImageUrl

	measure _slicer_defence_gif =
			
			"data:image/gif;base64,R0lGODlhgACAAPcAAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP4AAP4AAP4AAP4AAP4A"
		lineageTag: a0ac8694-1b0c-48c6-b25e-2b58e5fbbcda
		dataCategory: ImageUrl

	column metrics
		dataType: string
		lineageTag: ea5342d3-216f-46a3-a684-6374b0eac9e0
		summarizeBy: none
		sourceColumn: metrics

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromList(
				        {"Attack", "Defense", "Passing"},
				        Splitter.SplitByNothing(),
				        {"metrics"}
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"metrics", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

