table _measures
	lineageTag: 3b5b4d14-7f87-449d-ba5c-3418c25ab9f7

	measure _color_list_slicer = ```
			
			VAR seleccion = SELECTEDVALUE(_field_parameters[Parameter Group])
			RETURN
			    SWITCH(
			        TRUE(),
			        seleccion = "Attack", "#E74C3C",       // Rojo suave (Tomato Red)
			        seleccion = "Defense", "#5DADE2",      // Celeste (Sky Blue)
			        seleccion = "Passing", "#27AE60",
			        seleccion = "Goalkeeper", "#27AE60",         // Verde amigable (Emerald)
			        "#D5D8DC"                              // Gris claro por defecto
			    )
			
			```
		lineageTag: e25b4956-fa3a-4c2b-a95a-33c29d55c192
		dataCategory: ImageUrl

	measure _trophy_gif =
			
			"data:image/gif;base64,R0lGODlhgACAAPcAAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8A"
		displayFolder: _gif_and_photos
		lineageTag: c9e58679-e696-4f79-8733-6c5292967771
		dataCategory: Uncategorized

	measure _report_gif =
			
			"data:image/gif;base64,R0lGODlhgACAAPcAAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP4AAP4AAP4AAO0AAA8A"
		displayFolder: _gif_and_photos
		lineageTag: a07eda6f-cd89-4862-b425-dbe0d367cd2a
		dataCategory: ImageUrl

	measure card_term_1_metric_selected = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", SUM(statistics_attack[Goals]),
			        "Defense", SUM(statistics_defense[Tackles]),
			        "Passing", SUM(statistics_passing[Passes]),
			        0
			    )
			
			```
		formatString: 0
		displayFolder: _visuals
		lineageTag: d39bd00d-0a95-4959-822a-72ed02b7fc8d

	measure _page_color_team = ```
			
			SWITCH(
			    SELECTEDVALUE(dim_players[Equipo]),
			    "Arsenal", "#EF0107",            -- Rojo Arsenal
			    "Aston Villa", "#670E36",        -- Bord oscuro
			    "Bournemouth", "#DA291C",        -- Rojo intenso
			    "Brentford", "#E30613",          -- Rojo
			    "Brighton", "#0057B8",           -- Azul Brighton
			    "Burnley", "#6C1D45",            -- Bord clsico
			    "Chelsea", "#034694",            -- Azul Chelsea
			    "Crystal Palace", "#1B458F",     -- Azul fuerte
			    "Everton", "#003399",            -- Azul Everton
			    "Fulham", "#000000",             -- Negro
			    "Liverpool", "#C8102E",          -- Rojo Liverpool
			    "Ipswich Town", "#EE2737",         -- Rojo claro
			    "Manchester City", "#6CABDD",    -- Celeste City
			    "Manchester United", "#DA291C",  -- Rojo United
			    "Newcastle United", "#241F20",   -- Negro Newcastle
			    "Nottingham Forest", "#E53233",  -- Rojo
			    "Southampton", "#EE2737",   -- Rojo claro
			    "Tottenham Hotspur", "#132257",  -- Azul oscuro
			    "West Ham", "#7A263A",    -- Bord clsico
			    "Wolves", "#FDB913", -- Amarillo Wolves
			    "#BFBFBF"                         -- Color por defecto (gris claro)
			)
			
			```
		displayFolder: _page_design
		lineageTag: b6c793fe-cf98-4457-9d6b-879c9d93160f

	measure _selected_player_image =
			
			SELECTEDVALUE(dim_players[image URL])
		lineageTag: 9b585a04-967c-4f39-987e-d29d4e4771c4

	measure card_1_top_player = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			VAR _playerAttack = 
			    CALCULATE(
			        MAX(dim_players[Player]),
			        TOPN(1, statistics_attack, statistics_attack[Goals], DESC)
			    )
			VAR _playerDefense = 
			    CALCULATE(
			        MAX(dim_players[Player]),
			        TOPN(1, statistics_defense, statistics_defense[Tackles], DESC)
			    )
			VAR _playerPassing = 
			    CALCULATE(
			        MAX(dim_players[Player]),
			        TOPN(1, statistics_passing, statistics_passing[Passes], DESC)
			    )
			VAR _playerGoalkeeper = 
			    CALCULATE(
			        MAX(dim_players[Player]),
			        TOPN(1, statistics_goalkeeping, statistics_goalkeeping[Saves], DESC)
			    )
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", _playerAttack,
			        "Defense", _playerDefense,
			        "Passing", _playerPassing,
			        "Goalkeeper", _playerGoalkeeper,
			        "N/A"
			    )
			
			```
		lineageTag: eb39ee50-9ed1-44f5-a332-14a7cfa43f83

	measure title_card_5_metric_selected =
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", "Goals",
			        "Defense", "Tackles",
			        "Passing", "Assists",
			        "Goalkeeper", "Saves",
			        "None"
			    )
		lineageTag: 8de94784-579f-4e2e-8bc7-c6c2fdd74c22

	measure card_term_2_metric_selected =
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", SUM(statistics_attack[Goals opportunities created]),
			        "Defense", SUM(statistics_defense[Interceptions]),
			        "Passing", SUM(statistics_passing[Assists]),
			        0
			    )
		formatString: 0
		displayFolder: _visuals
		lineageTag: 7820b16e-8757-4ef3-8d7c-d93cbaad2299

	measure card_term_3_metric_selected =
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", SUM(statistics_attack[On target]),
			        "Defense", SUM(statistics_defense[Clearense]),
			        "Passing", SUM(statistics_passing[Key passes]),
			        0
			    )
		formatString: 0
		displayFolder: _visuals
		lineageTag: 2818d1c1-8dc7-415f-b415-da9599ed6f15

	measure _team_rank_term_1 = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			VAR _rank =
			    SWITCH(
			        _selected,
			        "Attack", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_attack[Goals])),
			                ,
			                DESC
			            ),
			        "Defense", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_defense[Tackles])),
			                ,
			                DESC
			            ),
			        "Passing", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_passing[Passes])),
			                ,
			                DESC
			            ),
			        "Goalkeeper", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_goalkeeping[Saves])),
			                ,
			                DESC
			            ),
			        BLANK()
			    )
			RETURN 
			"#" & _rank & " in the league"
			
			```
		displayFolder: _visuals
		lineageTag: 271d1bc6-59b0-494c-a3c2-34bae50e06d9

	measure _team_rank_term_2 = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			VAR _rank =
			    SWITCH(
			        _selected,
			        "Attack", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_attack[Goals opportunities created])),
			                ,
			                DESC
			            ),
			        "Defense", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_defense[Interceptions])),
			                ,
			                DESC
			            ),
			        "Passing", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_passing[Assists])),
			                ,
			                DESC
			            )
			    )
			RETURN 
			"#" & _rank & " in the league"
			```
		displayFolder: _visuals
		lineageTag: d05c8890-0728-4e10-9b46-8d9a43ccc6f6

	measure _team_rank_term_3 = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			VAR _rank =
			    SWITCH(
			        _selected,
			        "Attack", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_attack[On target])),
			                ,
			                DESC
			            ),
			        "Defense", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_defense[Clearense])),
			                ,
			                DESC
			            ),
			        "Passing", 
			            RANKX(
			                ALL(dim_teams[Team]),
			                CALCULATE(SUM(statistics_passing[Key passes])),
			                ,
			                DESC
			            )
			    )
			RETURN 
			"#" & _rank & " in the league"
			```
		displayFolder: _visuals
		lineageTag: 5b210599-aa12-4df9-850c-109b35659b37

	measure _title_card_term_1 = ```
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", "Goals",
			        "Defense", "Tackles",
			        "Passing", "Passes"
			    )
			
			```
		displayFolder: _visuals
		lineageTag: 63df5699-835e-41dc-ad23-f97e166f7d05

	measure _title_card_term_2 =
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", "Goal opportunities created",
			        "Defense", "Interceptions",
			        "Passing", "Assists"
			    )
		displayFolder: _visuals
		lineageTag: 49f508af-35c2-43b7-b882-866e2976af7f

	measure _title_card_term_3 =
			
			VAR _selected = SELECTEDVALUE(_field_parameters[Parameter Group])
			
			RETURN
			    SWITCH(
			        _selected,
			        "Attack", "Shoots on target",
			        "Defense", "Clearenses",
			        "Passing", "Key passes"
			    )
		displayFolder: _visuals
		lineageTag: 3990a58f-1072-443c-971e-966cb0665444

	column metrics
		dataType: string
		lineageTag: ea5342d3-216f-46a3-a684-6374b0eac9e0
		summarizeBy: none
		sourceColumn: metrics

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromList(
				        {"Attack", "Defense", "Passing"},
				        Splitter.SplitByNothing(),
				        {"metrics"}
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"metrics", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

